#!/usr/bin/bash

# If any command exits with a non-zero result code, exit immediately
set -e
set -o pipefail

. config
ensure_we_are_hot_node

for FILENAME in $(ls $SHARE/*.addr); do
  ADDR=$(cat $FILENAME)
  echo " "
  echo $(basename $FILENAME)"    "$ADDR
  cardano-cli query utxo --address $ADDR $NETWORK1 $NETWORK2
done
echo " "
echo "Done"

